#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-yapf
Version  : 0.40.2
Release  : 17
URL      : https://files.pythonhosted.org/packages/b9/14/c1f0ebd083fddd38a7c832d5ffde343150bd465689d12c549c303fbcd0f5/yapf-0.40.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/b9/14/c1f0ebd083fddd38a7c832d5ffde343150bd465689d12c549c303fbcd0f5/yapf-0.40.2.tar.gz
Summary  : A formatter for Python code
Group    : Development/Tools
License  : Apache-2.0 Python-2.0
Requires: pypi-yapf-bin = %{version}-%{release}
Requires: pypi-yapf-license = %{version}-%{release}
Requires: pypi-yapf-python = %{version}-%{release}
Requires: pypi-yapf-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# YAPF
<p align="center">
<a href="https://badge.fury.io/py/yapf"><img alt="PyPI Version" src="https://badge.fury.io/py/yapf.svg"></a>
<a href="https://github.com/google/yapf/actions/workflows/ci.yml"><img alt="Build Status" src="https://github.com/google/yapf/actions/workflows/ci.yml/badge.svg"></a>
<a href="https://github.com/google/yapf/actions/workflows/pre-commit.yml"><img alt="Actions Status" src="https://github.com/google/yapf/actions/workflows/pre-commit.yml/badge.svg"></a>
<a href="https://coveralls.io/github/google/yapf?branch=main"><img alt="Coverage Status" src="https://coveralls.io/repos/github/google/yapf/badge.svg?branch=main"></a>
</p>

%package bin
Summary: bin components for the pypi-yapf package.
Group: Binaries
Requires: pypi-yapf-license = %{version}-%{release}

%description bin
bin components for the pypi-yapf package.


%package license
Summary: license components for the pypi-yapf package.
Group: Default

%description license
license components for the pypi-yapf package.


%package python
Summary: python components for the pypi-yapf package.
Group: Default
Requires: pypi-yapf-python3 = %{version}-%{release}

%description python
python components for the pypi-yapf package.


%package python3
Summary: python3 components for the pypi-yapf package.
Group: Default
Requires: python3-core
Provides: pypi(yapf)
Requires: pypi(importlib_metadata)
Requires: pypi(platformdirs)
Requires: pypi(tomli)

%description python3
python3 components for the pypi-yapf package.


%prep
%setup -q -n yapf-0.40.2
cd %{_builddir}/yapf-0.40.2
pushd ..
cp -a yapf-0.40.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1695655743
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-yapf
cp %{_builddir}/yapf-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-yapf/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/yapf-%{version}/third_party/yapf_third_party/_ylib2to3/LICENSE %{buildroot}/usr/share/package-licenses/pypi-yapf/8482348f12824b36fba59883f9dd7fe03c1f86ca || :
cp %{_builddir}/yapf-%{version}/third_party/yapf_third_party/yapf_diff/LICENSE %{buildroot}/usr/share/package-licenses/pypi-yapf/76cdb6c64722fbcd432e868ee1498e304e967204 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/yapf
/usr/bin/yapf-diff

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-yapf/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/pypi-yapf/76cdb6c64722fbcd432e868ee1498e304e967204
/usr/share/package-licenses/pypi-yapf/8482348f12824b36fba59883f9dd7fe03c1f86ca

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
