#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : yapf
Version  : 0.31.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/85/60/8532f7ca17cea13de00e80e2fe1e6bd59a9379856706a027536b19daf0d3/yapf-0.31.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/85/60/8532f7ca17cea13de00e80e2fe1e6bd59a9379856706a027536b19daf0d3/yapf-0.31.0.tar.gz
Summary  : A formatter for Python code.
Group    : Development/Tools
License  : Apache-2.0
Requires: yapf-bin = %{version}-%{release}
Requires: yapf-license = %{version}-%{release}
Requires: yapf-python = %{version}-%{release}
Requires: yapf-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
YAPF
        ====

%package bin
Summary: bin components for the yapf package.
Group: Binaries
Requires: yapf-license = %{version}-%{release}

%description bin
bin components for the yapf package.


%package license
Summary: license components for the yapf package.
Group: Default

%description license
license components for the yapf package.


%package python
Summary: python components for the yapf package.
Group: Default
Requires: yapf-python3 = %{version}-%{release}

%description python
python components for the yapf package.


%package python3
Summary: python3 components for the yapf package.
Group: Default
Requires: python3-core
Provides: pypi(yapf)

%description python3
python3 components for the yapf package.


%prep
%setup -q -n yapf-0.31.0
cd %{_builddir}/yapf-0.31.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637358338
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/yapf
cp %{_builddir}/yapf-0.31.0/LICENSE %{buildroot}/usr/share/package-licenses/yapf/2b8b815229aa8a61e483fb4ba0588b8b6c491890
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/yapf
/usr/bin/yapf-diff

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/yapf/2b8b815229aa8a61e483fb4ba0588b8b6c491890

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
